//Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

//Users
export const CALL_START = 'CALL_START';
export const CALL_SUCCESS = 'CALL_SUCCESS';
export const CALL_FAIL = 'CALL_FAIL';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_USERS = 'GET_USERS';
export const DELETE_USER = 'DELETE_USER';
export const CREATE_USER = 'CREATE_USER';
export const FILTER_USERS = 'FILTER_USERS';
export const FILTER_FULLNAME = 'FILTER_FULLNAME';
export const CACHED_USERS = 'CACHED_USERS';
export const FILTER_PRODUCT_BY_SEARCH_BAR = 'FILTER_PRODUCT_BY_SEARCH_BAR';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
//sellers
export const GET_SELLERS = "GET_SELLERS";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const FILTER_APPOINTMENTS = "FILTER_APPOINTMENTS";
export const FILTER_SELLER = "FILTER_SELLER";
export const FILTER_CUSTOMERS = "FILTER_CUSTOMERS";
export const FILTER_CUSTOMERS_BY_YEAR = "FILTER_CUSTOMERS_BY_YEAR";
export const ERROR = "ERROR";
export const LOADING = "LOADING";
//Photografers
export const GET_PHOTOGRAFERS = "GET_PHOTOGRAFERS";
export const FILTER_PHOTO = "FILTER_PHOTO";
